//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfWinMirror.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfWinMirror.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string buttonClose_ToolTip {
            get {
                return ResourceManager.GetString("buttonClose_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string buttonMaximize_ToolTip {
            get {
                return ResourceManager.GetString("buttonMaximize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string buttonMinimize_ToolTip {
            get {
                return ResourceManager.GetString("buttonMinimize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string buttonRestore_ToolTip {
            get {
                return ResourceManager.GetString("buttonRestore_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load the image file!! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrMsgFailedToLoadImage {
            get {
                return ResourceManager.GetString("ErrMsgFailedToLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save the image file!! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrMsgFailedToSaveImage {
            get {
                return ResourceManager.GetString("ErrMsgFailedToSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;Invalid Window Handle&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidWindowHandle {
            get {
                return ResourceManager.GetString("InvalidWindowHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About this application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemAboutThisApp_Header {
            get {
                return ResourceManager.GetString("menuItemAboutThisApp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemAppClose_Header {
            get {
                return ResourceManager.GetString("menuItemAppClose_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Black に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemBackgroundPatternBlack_Header {
            get {
                return ResourceManager.GetString("menuItemBackgroundPatternBlack_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Gray に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemBackgroundPatternGray_Header {
            get {
                return ResourceManager.GetString("menuItemBackgroundPatternGray_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Lattice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemBackgroundPatternLattice_Header {
            get {
                return ResourceManager.GetString("menuItemBackgroundPatternLattice_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemBackgroundPatternNone_Header {
            get {
                return ResourceManager.GetString("menuItemBackgroundPatternNone_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemBackgroundPatternRoot_Header {
            get {
                return ResourceManager.GetString("menuItemBackgroundPatternRoot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _White に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemBackgroundPatternWhite_Header {
            get {
                return ResourceManager.GetString("menuItemBackgroundPatternWhite_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Brightness to opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemEffectBrightnessToOpacity_Header {
            get {
                return ResourceManager.GetString("menuItemEffectBrightnessToOpacity_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Darkness to opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemEffectDarknessToOpacity_Header {
            get {
                return ResourceManager.GetString("menuItemEffectDarknessToOpacity_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Grayscale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemEffectGrayscale_Header {
            get {
                return ResourceManager.GetString("menuItemEffectGrayscale_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemEffectNone_Header {
            get {
                return ResourceManager.GetString("menuItemEffectNone_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Negative (_Invert) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemEffectNPInvert_Header {
            get {
                return ResourceManager.GetString("menuItemEffectNPInvert_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Effect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemEffectRoot_Header {
            get {
                return ResourceManager.GetString("menuItemEffectRoot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit window to captured image size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemFitWindowToImage_Header {
            get {
                return ResourceManager.GetString("menuItemFitWindowToImage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Frame rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemFrameRateRoot_Header {
            get {
                return ResourceManager.GetString("menuItemFrameRateRoot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _0 (Stop) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemFrameRateStop_Header {
            get {
                return ResourceManager.GetString("menuItemFrameRateStop_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Horizontal reverse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemHorizontalReverse_Header {
            get {
                return ResourceManager.GetString("menuItemHorizontalReverse_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load image file as background... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemLoadImage_Header {
            get {
                return ResourceManager.GetString("menuItemLoadImage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Load preset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemLoadPresetRoot_Header {
            get {
                return ResourceManager.GetString("menuItemLoadPresetRoot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemOpacityRoot_Header {
            get {
                return ResourceManager.GetString("menuItemOpacityRoot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open the folder includes settings file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemOpenSettingsIncludeDir_Header {
            get {
                return ResourceManager.GetString("menuItemOpenSettingsIncludeDir_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemReset_Header {
            get {
                return ResourceManager.GetString("menuItemReset_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save captured image _as... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemSaveImageAs_Header {
            get {
                return ResourceManager.GetString("menuItemSaveImageAs_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save preset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemSavePresetRoot_Header {
            get {
                return ResourceManager.GetString("menuItemSavePresetRoot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save window list as... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemSaveWinListAs_Header {
            get {
                return ResourceManager.GetString("menuItemSaveWinListAs_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale factor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemScaleFactorRoot_Header {
            get {
                return ResourceManager.GetString("menuItemScaleFactorRoot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target _window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemTargetWindowRoot_Header {
            get {
                return ResourceManager.GetString("menuItemTargetWindowRoot_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Transparent mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemTransparentMode_Header {
            get {
                return ResourceManager.GetString("menuItemTransparentMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Vertical reverse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuItemVerticalReverse_Header {
            get {
                return ResourceManager.GetString("menuItemVerticalReverse_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - [Transparent Mode] (T Key to Toggle) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TransparentMode {
            get {
                return ResourceManager.GetString("TransparentMode", resourceCulture);
            }
        }
    }
}
